/*
 * test_brain.cpp
 *
 *  Created on: May 24, 2019
 *      Author: bartlomiej
 */

#include "catch.hpp"
#include "../src/bot/brain.hpp"
#include "../src/bot/screen_capture.hpp"

namespace test {

using namespace brain;

SCENARIO( "bot algorithm test" ) {

    GIVEN( "bot brain object, game state structure generated by a mock object, empty bot decisions mock object" ) {

    	model::GameState game_state;
    	bot::ScreenCapture screen_capture;
    	model::ActionScenario bot_decisions;
    	screen_capture.capture_screen( game_state );
    	Brain brain( game_state );
    	REQUIRE( bot_decisions.empty() );

        WHEN( "a game round is played" ) {

        	brain.play_round( bot_decisions );
        	THEN( "the bot has made some decisions" ) {
                REQUIRE( !bot_decisions.empty() );
            }
        }
    }
}

}// end namespace test


